// <auto-generated />
using System;
using BasketApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BasketApp.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220803211439_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BasketApp.Core.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2022, 8, 3, 21, 14, 39, 764, DateTimeKind.Utc).AddTicks(1805),
                            Name = "Bilgisayar",
                            Stock = 20,
                            UnitPrice = 100m
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2022, 8, 3, 21, 14, 39, 764, DateTimeKind.Utc).AddTicks(1809),
                            Name = "Buzdolabı",
                            Stock = 10,
                            UnitPrice = 600m
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2022, 8, 3, 21, 14, 39, 764, DateTimeKind.Utc).AddTicks(1811),
                            Name = "Çamaşır Makinesi",
                            Stock = 30,
                            UnitPrice = 100m
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2022, 8, 3, 21, 14, 39, 764, DateTimeKind.Utc).AddTicks(1812),
                            Name = "Elektrikli Süpürge",
                            Stock = 20,
                            UnitPrice = 2500m
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2022, 8, 3, 21, 14, 39, 764, DateTimeKind.Utc).AddTicks(1814),
                            Name = "Bulaşık Makinesi",
                            Stock = 40,
                            UnitPrice = 6600m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
